/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package buscaminas;

import buscaminas.Casilla;
import buscaminas.Tablero;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import java.util.function.Consumer;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author chama
 */
public class FrmJuego extends javax.swing.JFrame {

    int numFilas = 10;
	int numColumnas = 10;
	int numMinas = 10;
	JButton[][] botonesTablero;
	
	Tablero tablero;
	
    /**
     * Creates new form FrmJuego
     */
    public FrmJuego() {
        initComponents();
        juegoNuevo();
    }
    
    void descargarControles()
    {
        if(botonesTablero!=null)
        {
            for(int i = 0; i < botonesTablero.length; i++)
            {
                for(int j = 0; j< botonesTablero[i].length; i++)
                {
                    if(botonesTablero[i]!=null)
                    {
                        getContentPane().remove(botonesTablero[i][j]);
                    }
                }
            }
        }
    }
    
    private void juegoNuevo()
    {
        descargarControles();
        cargarControles();
        crearTablero();
        repaint();
    }
    
    private void crearTablero()
    {
    	tablero = new Tablero(numFilas, numColumnas, numMinas);
    	tablero.setEventoPartidaPerdida(new Consumer<List<Casilla>>() {
			
			@Override
			public void accept(List<Casilla> t) {
				for(Casilla casillasConMina: t)
				{
					botonesTablero[casillasConMina.getPosFila()][casillasConMina.getPosColumna()].setText("*");
				}
			}
		});
    	tablero.setEventoPartidaGanada(new Consumer<List<Casilla>>() {
		
    		@Override
    		public void accept(List<Casilla> t)
    		{
    			for(Casilla casillaConMina: t)
    			{
    				botonesTablero[casillaConMina.getPosFila()][casillaConMina.getPosColumna()].setText(":)");
    			}
    		}
    	});
    	
    	tablero.setEventoCasillaAbierta(new Consumer<Casilla>() {
    		
    		@Override
    		public void accept(Casilla t)
    		{
    			botonesTablero[t.getPosFila()][t.getPosColumna()].setEnabled(false);
    			botonesTablero[t.getPosFila()][t.getPosColumna()].setText(t.getMinasAlrededor()==0?"":t.getMinasAlrededor()+"");
    		}
    	});
    }
    
    private void cargarControles()
    {
    	int posXReferencia = 25;
    	int posYReferencia=25;
    	int anchoControl=30;
    	int altoControl=30;
    	
    	botonesTablero = new JButton[numFilas][numColumnas];
    	for(int i = 0; i < botonesTablero.length; i++)
    	{
    		for(int j = 0; j<botonesTablero[i].length;j++)
    		{
    			botonesTablero[i][j] = new JButton();
    			botonesTablero[i][j].setName(i+","+j);
    			botonesTablero[i][j].setBorder(null);
    			if(i==0 && j==0)
    			{
    				botonesTablero[i][j].setBounds(posXReferencia,posYReferencia,anchoControl,altoControl);
 
    			}else if( i==0 && j!=0)
    			{
    				botonesTablero[i][j].setBounds(botonesTablero[i][j-1].getX()+botonesTablero[i][j-1].getWidth(),posYReferencia,anchoControl,altoControl);
    			}else
    			{
    				botonesTablero[i][j].setBounds(botonesTablero[i-1][j].getX(),botonesTablero[i-1][j].getY() + botonesTablero[i-1][j].getHeight(),anchoControl,altoControl);
    			}
    			botonesTablero[i][j].addActionListener(new ActionListener() {
					
					@Override
					public void actionPerformed(ActionEvent e) {
						btnClick(e);
						
					}
				});
    			getContentPane().add(botonesTablero[i][j]);
    		}
    	} 
        this.setSize(botonesTablero[numFilas-1][numColumnas-1].getX() + botonesTablero[numFilas-1][numColumnas-1].getWidth()+40,
                botonesTablero[numFilas-1][numColumnas-1].getY() + botonesTablero[numFilas-1][numColumnas-1].getHeight() + 90);
    }
    
    private void btnClick(ActionEvent e)
    {
    	JButton btn = (JButton)e.getSource();
    	String[] coordenada = btn.getName().split(",");
    	int posFila=Integer.parseInt(coordenada[0]);
    	int posColumna=Integer.parseInt(coordenada[1]);
    	tablero.seleccionarCasilla(posFila, posColumna);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuNuevoJuego = new javax.swing.JMenu();
        Tamano = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuNuevoJuego.setText("Juego");
        menuNuevoJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNuevoJuegoActionPerformed(evt);
            }
        });

        Tamano.setText("Tamaño");
        Tamano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TamanoActionPerformed(evt);
            }
        });
        menuNuevoJuego.add(Tamano);

        jMenuItem1.setText("Nuevo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuNuevoJuego.add(jMenuItem1);

        jMenuBar1.add(menuNuevoJuego);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 607, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 444, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void menuNuevoJuegoActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
        
    }                                              

    private void TamanoActionPerformed(java.awt.event.ActionEvent evt) {                                       
                // TODO add your handling code here:
        int num = Integer.parseInt(JOptionPane.showInputDialog("Digite tamanho de la matriz, n* n"));
        this.numFilas=num;
        this.numColumnas=num;
    }                                      

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmJuego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JMenuItem Tamano;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu menuNuevoJuego;
    // End of variables declaration                   
}
